### PR TITLE
New translations!

### PR DESCRIPTION
**Pull request by eggsywashere**
eggsy.

### CODE REVIEW

**Comment by Bas950** [comment]
I thought you had to add it to English not source or I else I will have to change my PR xD

**Comment by eggsywashere** [comment]
@Bas950 I have no idea tbh
image

**Comment by Bas950** [comment]
image
Yea I see...

**Comment by eggsywashere** [comment]
rip your PR xd

**Comment by Bas950** [comment]
yerp... f me xD

**Pull request merged**
